const gamesData = {
    platinados: [
        { name: "A Hat In Time", isDLC: false, isMod: false },
        { name: "Human Fall Flat", isDLC: false, isMod: false },
        { name: "Rubber Bandits", isDLC: false, isMod: false },
        { name: "Gang Beasts", isDLC: false, isMod: false }
    ],
    zerados: [
        { name: "Minecraft", isDLC: false, isMod: false },
        { name: "Subnautica", isDLC: false, isMod: false },
        { name: "Celeste", isDLC: false, isMod: false },
        { name: "Undertale", isDLC: false, isMod: false },
        { name: "Borderlands 2", isDLC: false, isMod: false },
        { name: "Watch Dogs", isDLC: false, isMod: false },
        { name: "Watch Dogs 2", isDLC: false, isMod: false },
        { name: "Super Mario 64", isDLC: false, isMod: false },
        { name: "Terraria", isDLC: false, isMod: false },
        { name: "Super Mario World", isDLC: false, isMod: false },
        { name: "Super Mario 64 DS", isDLC: false, isMod: false },
        { name: "Super Mario Odyssey", isDLC: false, isMod: false },
        { name: "New Super Mario Bros. DS", isDLC: false, isMod: false },
        { name: "New Super Mario Bros. Wii", isDLC: false, isMod: false },
        { name: "New Super Mario Bros. 2", isDLC: false, isMod: false },
        { name: "Newer Super Mario Bros. DS", isDLC: false, isMod: true },
        { name: "Kirby Triple Deluxe", isDLC: false, isMod: false },
        { name: "Kirby & The Amazing Mirror", isDLC: false, isMod: false },
        { name: "Portal Knights", isDLC: false, isMod: false },
        { name: "Mario Kart 7", isDLC: false, isMod: false },
        { name: "Mario Kart DS", isDLC: false, isMod: false },
        { name: "Mario Kart 8 Deluxe", isDLC: false, isMod: false },
        { name: "Super Mario 3D Land", isDLC: false, isMod: false },
        { name: "Captain Toad: Treasure Tracker", isDLC: false, isMod: false },
        { name: "Payday 2", isDLC: false, isMod: false },
        { name: "Grand Theft Auto San Andreas", isDLC: false, isMod: false },
        { name: "Plants vs. Zombies 1", isDLC: false, isMod: false },
        { name: "Plants vs. Zombies 2", isDLC: false, isMod: false },
        { name: "Plants vs. Zombies Garden Warfare 2", isDLC: false, isMod: false },
        { name: "Plants vs. Zombies Battle for Neighborville", isDLC: false, isMod: false },
        { name: "Super Mario Sunshine", isDLC: false, isMod: false },
        { name: "LEGO Marvel's Avengers", isDLC: false, isMod: false },
        { name: "The LEGO Movie 2 Videogame", isDLC: false, isMod: false },
        { name: "LEGO Batman 3: Beyond Gotham", isDLC: false, isMod: false },
        { name: "LEGO Worlds", isDLC: false, isMod: false },
        { name: "Steamworld Dig", isDLC: false, isMod: false },
        { name: "Half-Life", isDLC: false, isMod: false },
        { name: "Borderlands", isDLC: false, isMod: false },
        { name: "LEGO Batman 2: DC Super Heroes", isDLC: false, isMod: false },
        { name: "Rise of The Tomb Raider", isDLC: false, isMod: false },
        { name: "LEGO City Undercover: The Chase Begins", isDLC: false, isMod: false },
        { name: "Terraria 3DS", isDLC: false, isMod: false },
        { name: "Zuma's Revenge", isDLC: false, isMod: false },
        { name: "Toy Story 3: The Video Game", isDLC: false, isMod: false },
        { name: "Sonic Generations", isDLC: false, isMod: false },
        { name: "Poochy & Yoshi's Woolly World", isDLC: false, isMod: false },
        { name: "New Super Mario Bros. U Deluxe", isDLC: false, isMod: false },
        { name: "Watch Dogs: Bad Blood", isDLC: true, isMod: false }
    ],
    biblioteca: [
        { name: "Borderlands GOTY Enhanced", isDLC: false, isMod: false },
        { name: "Borderlands 2", isDLC: false, isMod: false },
        { name: "Borderlands 3", isDLC: false, isMod: false },
        { name: "Borderlands: The Pre-Sequel", isDLC: false, isMod: false },
        { name: "Watch Dogs: Legion", isDLC: false, isMod: false },
        { name: "Subnautica: Below Zero", isDLC: false, isMod: false },
        { name: "Fantasy Life", isDLC: false, isMod: false },
        { name: "Dead Island", isDLC: false, isMod: false },
        { name: "Dead Island Riptide", isDLC: false, isMod: false },
        { name: "Super Mombo Quest", isDLC: false, isMod: false },
        { name: "Grand Theft Auto V", isDLC: false, isMod: false },
        { name: "Dying Light", isDLC: false, isMod: false },
        { name: "LEGO Marvel Super Heroes", isDLC: false, isMod: false },
        { name: "LEGO Marvel Super Heroes 2", isDLC: false, isMod: false },
        { name: "LEGO Indiana Jones: The Original Adventures", isDLC: false, isMod: false },
        { name: "LEGO Star Wars II", isDLC: false, isMod: false },
        { name: "LEGO Star Wars: The Complete Saga", isDLC: false, isMod: false },
        { name: "Half-Life 2", isDLC: false, isMod: false },
        { name: "The Forest", isDLC: false, isMod: false }
    ]
};
